spring.application.name=Plans_API

# DATA SOURCE PROPERTIES
spring.datasource.url=jdbc:h2:mem:stormdb
spring.datasource.username=sourav
spring.datasource.password=12345
spring.datasource.driver-class-name=org.h2.Driver

# Optional H2 Console Access
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

plan-api.messages.planSaveSucc=Plan Saved Successfully
plan-api.messages.planSaveFail=Plan Not Saved
plan-api.messages.planUpdateSucc=Plan Updated Successfully
plan-api.messages.planUpdateFail=Plan Not Updated
plan-api.messages.planDeleteSucc=Plan Deleted Successfully
plan-api.messages.planDeleteFail=Plan Not Deleted
plan-api.messages.planStatusChange=Plan Status Changed Successfully
plan-api.messages.planStatusChangeFail=Plan Status Change Failed